[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "mocks/=test/mocks/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
]
solc-version = "0.8.18"
ffi = true
fs_permissions = [{ access = "read", path = "./broadcast" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
